stages:
  - build

variables:
  REGISTRY: registry.wapos.com:5055

build:
  stage: build
  image: docker:latest
  script:
    - IMAGE="$REGISTRY/$CI_PROJECT_PATH/my-image:$CI_COMMIT_SHA"
    - docker build -t "$IMAGE" .
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $REGISTRY
    - docker push "$IMAGE"

